"""
Cookbook: Streaming Tool Call Arguments (tool_args.delta)

This example demonstrates how to use the ToolCallArgsDeltaEvent to receive
incremental updates of tool call arguments as they are generated by the model.
"""

import os
from pathlib import Path

# Load environment variables
from dotenv import load_dotenv

AGENTOS_DIR = Path("/Users/yooyi/Projects/agentos")
load_dotenv(AGENTOS_DIR / ".env")

from agno.agent import Agent
from agno.models.deepseek import DeepSeek
from agno.run.agent import (
    ToolCallArgsDeltaEvent,
    ToolCallStartedEvent,
    ToolCallCompletedEvent,
    ToolCallErrorEvent,
)


def multiply(x: int, y: int) -> int:
    """Multiply two numbers."""
    return x * y


def test_tool_call_args_delta():
    """Test streaming tool call argument deltas."""
    print("=" * 70)
    print("Test: Streaming Tool Call Arguments (tool_args.delta)")
    print("=" * 70)

    agent = Agent(
        model=DeepSeek(
            id="deepseek-chat",
            base_url="https://api.302.ai/v1",
            api_key=os.environ.get("DEEPSEEK_API_KEY"),
        ),
        tools=[multiply],
        stream_events=True,
        show_tool_calls=True,
    )

    # Track the complete arguments as they stream in
    complete_args = ""
    tool_calls_seen = set()

    print("\nRequest: Calculate 25 * 40")
    print("-" * 70)

    for chunk in agent.run("Calculate 25 * 40", stream=True):
        if isinstance(chunk, ToolCallStartedEvent):
            print(f"\n[ToolCallStartedEvent]")
            print(f"  tool_name: {chunk.tool.tool_name}")
            print(f"  tool_call_id: {chunk.tool.tool_call_id}")

        elif isinstance(chunk, ToolCallArgsDeltaEvent):
            # Track which tool call we're receiving
            if chunk.tool_call_id:
                tool_calls_seen.add(chunk.tool_call_id)

            delta = chunk.delta or ""
            complete_args += delta
            print(f"\n[ToolCallArgsDeltaEvent]")
            print(f"  tool_call_id: {chunk.tool_call_id or '(using tracked value)'}")
            print(
                f"  tool_call_name: {chunk.tool_call_name or '(using tracked value)'}"
            )
            print(f"  delta: {repr(delta)}")
            print(f"  accumulated: {complete_args}")

        elif isinstance(chunk, ToolCallCompletedEvent):
            print(f"\n[ToolCallCompletedEvent]")
            print(f"  tool_name: {chunk.tool.tool_name}")
            print(f"  result: {chunk.tool.result}")

        elif isinstance(chunk, ToolCallErrorEvent):
            print(f"\n[ToolCallErrorEvent]")
            print(f"  error: {chunk.error}")

    print("\n" + "=" * 70)
    print(f"Complete accumulated arguments: {complete_args}")
    print(f"Tool calls tracked: {len(tool_calls_seen)}")
    print("=" * 70)


def test_multiple_tool_calls():
    """Test streaming with multiple tool calls."""
    print("\n" + "=" * 70)
    print("Test: Multiple Streaming Tool Calls")
    print("=" * 70)

    def add(x: int, y: int) -> int:
        """Add two numbers."""
        return x + y

    def subtract(x: int, y: int) -> int:
        """Subtract two numbers."""
        return x - y

    agent = Agent(
        model=DeepSeek(
            id="deepseek-chat",
            base_url="https://api.302.ai/v1",
            api_key=os.environ.get("DEEPSEEK_API_KEY"),
        ),
        tools=[add, subtract],
        stream_events=True,
        show_tool_calls=True,
    )

    # Track each tool call's arguments separately
    tool_args_tracker: dict[str, str] = {}

    print("\nRequest: Add 100 and 200, then subtract 50 from the result")
    print("-" * 70)

    current_tool_id = None
    for chunk in agent.run(
        "Add 100 and 200, then subtract 50 from the result", stream=True
    ):
        if isinstance(chunk, ToolCallStartedEvent):
            current_tool_id = chunk.tool.tool_call_id
            print(f"\n[ToolCallStartedEvent] {chunk.tool.tool_name}")

        elif isinstance(chunk, ToolCallArgsDeltaEvent):
            # Update the current tool call's arguments
            if chunk.tool_call_id:
                current_tool_id = chunk.tool_call_id

            if current_tool_id:
                if current_tool_id not in tool_args_tracker:
                    tool_args_tracker[current_tool_id] = ""
                tool_args_tracker[current_tool_id] += chunk.delta or ""

            print(f"  [{current_tool_id[-8:]}...] {chunk.delta}")

        elif isinstance(chunk, ToolCallCompletedEvent):
            print(
                f"\n[ToolCallCompletedEvent] {chunk.tool.tool_name} = {chunk.tool.result}"
            )

    print("\n" + "=" * 70)
    print("Final accumulated arguments:")
    for tool_id, args in tool_args_tracker.items():
        print(f"  {tool_id}: {args}")
    print("=" * 70)


def test_partial_json_validation():
    """Demonstrate partial JSON validation as deltas arrive."""
    print("\n" + "=" * 70)
    print("Test: Partial JSON Validation")
    print("=" * 70)

    import json

    def calculate(a: int, b: int, operation: str = "multiply") -> dict:
        """Calculate the result of an operation."""
        if operation == "multiply":
            result = a * b
        elif operation == "add":
            result = a + b
        elif operation == "subtract":
            result = a - b
        else:
            result = None
        return {"result": result}

    agent = Agent(
        model=DeepSeek(
            id="deepseek-chat",
            base_url="https://api.302.ai/v1",
            api_key=os.environ.get("DEEPSEEK_API_KEY"),
        ),
        tools=[calculate],
        stream_events=True,
    )

    print("\nRequest: Multiply 15 by 25 using the calculate tool")
    print("-" * 70)
    print("\nStreaming with JSON validation:")
    print()

    complete_args = ""
    is_valid_partial = True

    for chunk in agent.run("Use calculate tool to multiply 15 by 25", stream=True):
        if isinstance(chunk, ToolCallArgsDeltaEvent):
            delta = chunk.delta or ""
            complete_args += delta

            # Check if partial JSON is valid so far
            is_valid_partial = True
            if complete_args.count("{") > complete_args.count("}"):
                is_valid_partial = False
            elif complete_args.rstrip().endswith(","):
                is_valid_partial = False

            status = "✓" if is_valid_partial else "✗"
            print(
                f"  {status} delta={repr(delta):30} accumulated={complete_args[:50]}..."
            )

            # Try to parse if it looks complete
            if complete_args.startswith("{") and complete_args.endswith("}"):
                try:
                    args = json.loads(complete_args)
                    print(f"\n  🎉 Complete valid JSON: {args}")
                    break
                except json.JSONDecodeError:
                    pass  # Not complete yet

    print("\n" + "=" * 70)


if __name__ == "__main__":
    test_tool_call_args_delta()
    test_multiple_tool_calls()
    test_partial_json_validation()
